### ISSUE TITLE
ubuntu1610 is not available

### ISSUE THREAD

**Issue by RevanthReddyT** [g0t4/aspnetcore-generator-api#4]
For swarm ubuntu1610 is not available so it does not work. 
So can we use ubuntu1704 ?

**Comment by g0t4** [comment]
Yup, should be fine, let me know if you have any trouble.


----------
On Sun, Oct 15, 2017 at 11:40 PM, Revanth Reddy T <notifications@github.com>
wrote:

For swarm ubuntu1610 is not available so it does not work.
So can we use ubuntu1704 ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/g0t4/aspnetcore-generator-api/issues/4>, or mute the
thread

**Comment by RevanthReddyT** [comment]
When I use ubuntu1610 it is asking for the following. Which one do we need to select?

1) en0: Wi-Fi (AirPort)
2) en1: Ethernet Adaptor (en1)
3) en2: Ethernet Adaptor (en2)
4) bridge0
5) p2p0
6) awdl0
==> m1: When choosing an interface, it is usually the one that is
==> m1: being used to connect to the internet.
    m1: Which interface should the network bridge to?

**Comment by g0t4** [comment]
The one that matches the prompt’s question.


----------
On Mon, Oct 16, 2017 at 10:12 AM, Revanth Reddy T <notifications@github.com>
wrote:

When I use ubuntu1610 it is asking for the following. Which one do we need
to select?

   1. en0: Wi-Fi (AirPort)
   2. en1: Ethernet Adaptor (en1)
   3. en2: Ethernet Adaptor (en2)
   4. bridge0
   5. p2p0
   6. awdl0
   ==> m1: When choosing an interface, it is usually the one that is
   ==> m1: being used to connect to the internet.
   m1: Which interface should the network bridge to?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/g0t4/aspnetcore-generator-api/issues/4#issuecomment-336899499>,
or mute the thread

**Comment by g0t4** [comment]
FYI for anyone that reads this thread, use box-cutter/ubuntu1610 and open `provision.sh` and change `test.docker.com` to `get.docker.com`
