### ISSUE TITLE
Getting error in swarm

### ISSUE THREAD

**Issue by RevanthReddyT** [g0t4/aspnetcore-generator-api#5]
On running vagrant up m1 w1 w3 
Getting following output 

Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'w1' up with 'virtualbox' provider...
Bringing machine 'w3' up with 'virtualbox' provider...
==> m1: Importing base box 'boxcutter/ubuntu1704'...
==> m1: Matching MAC address for NAT networking...
==> m1: Checking if box 'boxcutter/ubuntu1704' is up to date...
==> m1: Setting the name of the VM: swarm_m1_1508193978734_64274
==> m1: Clearing any previously set network interfaces...
==> m1: Specific bridge 'en0: Ethernet' not found. You may be asked to specify
==> m1: which network to bridge to.
==> m1: Available bridged network interfaces:
1) en0: Wi-Fi (AirPort)
2) en1: Ethernet Adaptor (en1)
3) en2: Ethernet Adaptor (en2)
4) bridge0
5) p2p0
6) awdl0
==> m1: When choosing an interface, it is usually the one that is
==> m1: being used to connect to the internet.
    m1: Which interface should the network bridge to? 1
==> m1: Preparing network interfaces based on configuration...
    m1: Adapter 1: nat
    m1: Adapter 2: bridged
==> m1: Forwarding ports...
    m1: 22 (guest) => 2222 (host) (adapter 1)
==> m1: Running 'pre-boot' VM customizations...
==> m1: Booting VM...
==> m1: Waiting for machine to boot. This may take a few minutes...
    m1: SSH address: 127.0.0.1:2222
    m1: SSH username: vagrant
    m1: SSH auth method: private key
    m1: 
    m1: Vagrant insecure key detected. Vagrant will automatically replace
    m1: this with a newly generated keypair for better security.
    m1: 
    m1: Inserting generated public key within guest...
    m1: Removing insecure key from the guest if it's present...
    m1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> m1: Machine booted and ready!
==> m1: Checking for guest additions in VM...
==> m1: Setting hostname...
==> m1: Configuring and enabling network interfaces...
==> m1: Mounting shared folders...
    m1: /vagrant => /Users/revantht/Projects/Innominds/Mobilogix/innominds_mobilogix_server/infra/swarm
==> m1: Running provisioner: shell...
    m1: Running: /var/folders/t8/gv0q03sd7vz0m17qd6g33b0r0000gn/T/vagrant-shell20171017-16023-1m1k1bw.sh
==> m1: curl: (6) Could not resolve host: test.docker.com
==> m1: usermod: group 'docker' does not exist
==> m1: /tmp/vagrant-shell: line 13: /etc/docker/daemon.json: No such file or directory
==> m1: --2017-10-16 22:48:36--  https://raw.githubusercontent.com/docker/docker/v17.05.0-ce/contrib/init/systemd/docker.service.rpm
==> m1: Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 
==> m1: 151.101.36.133
==> m1: Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.36.133|:443... 
==> m1: connected.
==> m1: HTTP request sent, awaiting response... 
==> m1: 200 OK
==> m1: Length: 
==> m1: 1140
==> m1:  (1.1K)
==> m1:  [text/plain]
==> m1: Saving to: '/lib/systemd/system/docker.service'
==> m1: 
==> m1:      0K
==> m1:  
==> m1: .
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1: 100%
==> m1:   331M
==> m1: =0s
==> m1: 
==> m1: 2017-10-16 22:48:38 (331 MB/s) - '/lib/systemd/system/docker.service' saved [1140/1140]
==> m1: Job for docker.service failed because the control process exited with error code.
==> m1: See "systemctl status docker.service" and "journalctl -xe" for details.
==> m1: Reading package lists...
==> m1: Building dependency tree...
==> m1: E: Unable to locate package ipvsadm
==> m1: E: Unable to locate package tree
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by g0t4** [comment]
Try the box-cutter/ubuntu1610 image instead


----------
On Mon, Oct 16, 2017 at 6:52 PM, Revanth Reddy T <notifications@github.com>
wrote:

On running vagrant up m1 w1 w3
Getting following output

Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'w1' up with 'virtualbox' provider...
Bringing machine 'w3' up with 'virtualbox' provider...
==> m1: Importing base box 'boxcutter/ubuntu1704'...
==> m1: Matching MAC address for NAT networking...
==> m1: Checking if box 'boxcutter/ubuntu1704' is up to date...
==> m1: Setting the name of the VM: swarm_m1_1508193978734_64274
==> m1: Clearing any previously set network interfaces...
==> m1: Specific bridge 'en0: Ethernet' not found. You may be asked to
specify
==> m1: which network to bridge to.
==> m1: Available bridged network interfaces:

   1. en0: Wi-Fi (AirPort)
   2. en1: Ethernet Adaptor (en1)
   3. en2: Ethernet Adaptor (en2)
   4. bridge0
   5. p2p0
   6. awdl0
   ==> m1: When choosing an interface, it is usually the one that is
   ==> m1: being used to connect to the internet.
   m1: Which interface should the network bridge to? 1
   ==> m1: Preparing network interfaces based on configuration...
   m1: Adapter 1: nat
   m1: Adapter 2: bridged
   ==> m1: Forwarding ports...
   m1: 22 (guest) => 2222 (host) (adapter 1)
   ==> m1: Running 'pre-boot' VM customizations...
   ==> m1: Booting VM...
   ==> m1: Waiting for machine to boot. This may take a few minutes...
   m1: SSH address: 127.0.0.1:2222
   m1: SSH username: vagrant
   m1: SSH auth method: private key
   m1:
   m1: Vagrant insecure key detected. Vagrant will automatically replace
   m1: this with a newly generated keypair for better security.
   m1:
   m1: Inserting generated public key within guest...
   m1: Removing insecure key from the guest if it's present...
   m1: Key inserted! Disconnecting and reconnecting using new SSH key...
   ==> m1: Machine booted and ready!
   ==> m1: Checking for guest additions in VM...
   ==> m1: Setting hostname...
   ==> m1: Configuring and enabling network interfaces...
   ==> m1: Mounting shared folders...
   m1: /vagrant =>
   /Users/revantht/Projects/Innominds/Mobilogix/innominds_mobilogix_server/infra/swarm
   ==> m1: Running provisioner: shell...
   m1: Running:
   /var/folders/t8/gv0q03sd7vz0m17qd6g33b0r0000gn/T/vagrant-shell20171017-16023-1m1k1bw.sh
   ==> m1: curl: (6) Could not resolve host: test.docker.com
   ==> m1: usermod: group 'docker' does not exist
   ==> m1: /tmp/vagrant-shell: line 13: /etc/docker/daemon.json: No such
   file or directory
   ==> m1: --2017-10-16 22:48:36--
   https://raw.githubusercontent.com/docker/docker/v17.05.0-ce/contrib/init/systemd/docker.service.rpm
   ==> m1: Resolving raw.githubusercontent.com (raw.githubusercontent.com
   )...
   ==> m1: 151.101.36.133
   ==> m1: Connecting to raw.githubusercontent.com (
   raw.githubusercontent.com)|151.101.36.133|:443...
   ==> m1: connected.
   ==> m1: HTTP request sent, awaiting response...
   ==> m1: 200 OK
   ==> m1: Length:
   ==> m1: 1140
   ==> m1: (1.1K)
   ==> m1: [text/plain]
   ==> m1: Saving to: '/lib/systemd/system/docker.service'
   ==> m1:
   ==> m1: 0K
   ==> m1:
   ==> m1: .
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1:
   ==> m1: 100%
   ==> m1: 331M
   ==> m1: =0s
   ==> m1:
   ==> m1: 2017-10-16 22:48:38 (331 MB/s) -
   '/lib/systemd/system/docker.service' saved [1140/1140]
   ==> m1: Job for docker.service failed because the control process exited
   with error code.
   ==> m1: See "systemctl status docker.service" and "journalctl -xe" for
   details.
   ==> m1: Reading package lists...
   ==> m1: Building dependency tree...
   ==> m1: E: Unable to locate package ipvsadm
   ==> m1: E: Unable to locate package tree
   The SSH command responded with a non-zero exit status. Vagrant
   assumes that this means the command failed. The output for this command
   should be in the log above. Please read the output to determine what
   went wrong.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/g0t4/aspnetcore-generator-api/issues/5>, or mute the
thread

**Comment by RevanthReddyT** [comment]
Yes I tried box-cutter/ubuntu1610 but geting following error.

Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'w1' up with 'virtualbox' provider...
Bringing machine 'w2' up with 'virtualbox' provider...
==> m1: Box 'box-cutter/ubuntu1610' could not be found. Attempting to find and install...
    m1: Box Provider: virtualbox
    m1: Box Version: >= 0
==> m1: Loading metadata for box 'box-cutter/ubuntu1610'
    m1: URL: https://vagrantcloud.com/box-cutter/ubuntu1610
==> m1: Adding box 'box-cutter/ubuntu1610' (v2.0.26) for provider: virtualbox
    m1: Downloading: https://vagrantcloud.com/box-cutter/boxes/ubuntu1610/versions/2.0.26/providers/virtualbox.box
==> m1: Successfully added box 'box-cutter/ubuntu1610' (v2.0.26) for 'virtualbox'!
==> m1: Importing base box 'box-cutter/ubuntu1610'...
==> m1: Matching MAC address for NAT networking...
==> m1: Checking if box 'box-cutter/ubuntu1610' is up to date...
==> m1: Setting the name of the VM: swarm_m1_1508220649905_83530
==> m1: Clearing any previously set network interfaces...
==> m1: Specific bridge 'en0: Ethernet' not found. You may be asked to specify
==> m1: which network to bridge to.
==> m1: Available bridged network interfaces:
1) en0: Wi-Fi (AirPort)
2) en1: Ethernet Adaptor (en1)
3) en2: Ethernet Adaptor (en2)
4) bridge0
5) p2p0
6) awdl0
==> m1: When choosing an interface, it is usually the one that is
==> m1: being used to connect to the internet.
    m1: Which interface should the network bridge to? 1
==> m1: Preparing network interfaces based on configuration...
    m1: Adapter 1: nat
    m1: Adapter 2: bridged
==> m1: Forwarding ports...
    m1: 22 (guest) => 2222 (host) (adapter 1)
==> m1: Running 'pre-boot' VM customizations...
==> m1: Booting VM...
==> m1: Waiting for machine to boot. This may take a few minutes...
    m1: SSH address: 127.0.0.1:2222
    m1: SSH username: vagrant
    m1: SSH auth method: private key
    m1: 
    m1: Vagrant insecure key detected. Vagrant will automatically replace
    m1: this with a newly generated keypair for better security.
    m1: 
    m1: Inserting generated public key within guest...
    m1: Removing insecure key from the guest if it's present...
    m1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> m1: Machine booted and ready!
==> m1: Checking for guest additions in VM...
==> m1: Setting hostname...
==> m1: Configuring and enabling network interfaces...
==> m1: Mounting shared folders...
    m1: /vagrant => /Users/revantht/Projects/Innominds/Mobilogix/innominds_mobilogix_server/infra/swarm
==> m1: Running provisioner: shell...
    m1: Running: /var/folders/t8/gv0q03sd7vz0m17qd6g33b0r0000gn/T/vagrant-shell20171017-24552-17pcvwu.sh
==> m1: # Executing docker install script, commit: 01c3179
==> m1: 
==> m1: Either your platform is not easily detectable or is not supported by this
==> m1: installer script.
==> m1: Please visit the following URL for more detailed installation instructions:
==> m1: 
==> m1: https://docs.docker.com/engine/installation/
==> m1: usermod: group 'docker' does not exist
==> m1: /tmp/vagrant-shell: line 13: /etc/docker/daemon.json: No such file or directory
==> m1: --2017-10-17 06:11:24--  https://raw.githubusercontent.com/docker/docker/v17.05.0-ce/contrib/init/systemd/docker.service.rpm
==> m1: Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 
==> m1: 151.101.8.133
==> m1: Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.8.133|:443... 
==> m1: connected.
==> m1: HTTP request sent, awaiting response... 
==> m1: 200 OK
==> m1: Length: 1140 (1.1K) [text/plain]
==> m1: Saving to: '/lib/systemd/system/docker.service'
==> m1: 
==> m1:      0K .                       
==> m1:              
==> m1:                  100%
==> m1:   502M=0s
==> m1: 2017-10-17 06:11:24 (502 MB/s) - '/lib/systemd/system/docker.service' saved [1140/1140]
==> m1: Job for docker.service failed because the control process exited with error code.
==> m1: See "systemctl status docker.service" and "journalctl -xe" for details.
==> m1: Reading package lists...
==> m1: Building dependency tree...
==> m1: E: Unable to locate package ipvsadm
==> m1: E: Unable to locate package tree
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by g0t4** [comment]
After changing to box-cutter/ubuntu11610, in `provision.sh` switch `test.docker.com` to `get.docker.com`, the stable version seems to install ok.

**Comment by RevanthReddyT** [comment]
Thank You it worked.

**Comment by RevanthReddyT** [comment]
After runing "docker stack deploy -c services/viz.yml viz"

when I open http://192.168.0.211:8090/  I am getting This site can’t be reached

Is ther any command to start it?

**Comment by g0t4** [comment]
Follow what I did in the videos, and look for any issues with the services
that the stack creates. Also validate IP addresses and ports


----------
On Tue, Oct 17, 2017 at 1:57 PM, Revanth Reddy T <notifications@github.com>
wrote:

After runing "docker stack deploy -c services/viz.yml viz"

when I open http://192.168.0.211:8090/ I am getting This site can’t be
reached

Is ther any command to start it?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/g0t4/aspnetcore-generator-api/issues/5#issuecomment-337311268>,
or mute the thread

**Comment by RevanthReddyT** [comment]
Yes, i follow the video. After "docker stack deploy -c services/viz.yml viz" it shows network and serviec is created.  But when I open http://192.168.0.211:8090/ I am getting This site can’t be reached.

Following is the out put in my system.

Revanths-MacBook-Pro-2:swarm revantht$ docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
35muevylfno0fh7tokrl48b5y *   m1                  Ready               Active              Leader
hfwcc2uw4xfh26j3vppsji7ie     w1                  Ready               Active              
nw106pyyqofrlcpqxyio82k6r     w2                  Ready               Active              
Revanths-MacBook-Pro-2:swarm revantht$ highlight services/viz.yml 
-bash: highlight: command not found
Revanths-MacBook-Pro-2:swarm revantht$ docker stack deploy -c services/viz.yml viz
Creating network viz_default
Creating service viz_viz
Revanths-MacBook-Pro-2:swarm revantht$

**Comment by RevanthReddyT** [comment]
The issue is because of manomarks/visualizer is not avalible. "This repository moved to dockersamples/visualizer as an official Docker Sample."

1. I have changed manomarks/visualizer to dockersamples/visualizer in viz.yml file.
2. Before "docker stack deploy -c services/viz.yml viz"  I execute "docker pull dockersamples/visualizer"

This fixed the issue.

**Comment by g0t4** [comment]
Thanks for sharing, seems like everything gets yanked when renamed!


----------
On Sun, Oct 22, 2017 at 17:38, Revanth Reddy T <notifications@github.com>
wrote:

Closed #5 <https://github.com/g0t4/aspnetcore-generator-api/issues/5>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/g0t4/aspnetcore-generator-api/issues/5#event-1304682798>,
or mute the thread
